# Required
github_username: "hanumanthreddy022@gmail.com"
github_password: "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"
# Optional
github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/two_factor_authentication/verify
