# Required
github_username: "hanureddy022@gmail.com"
github_password: "Welcome2022-"
# Optional
github_totp_seed: "ABCDEF1234567890" # Obtained via https://github.com/settings/two_factor_authentication/verify
